version: "3.9"
services:
  web:
    build: 
      context: .
      # dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=ReadingAlpha
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./services/database/sql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ReadingAlpha
      MYSQL_USER: user
      MYSQL_PASSWORD: password
