version: "3.9"
services:
  web:
    build: 
      context: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    # environment:
    #   - DB_NAME=reading-alpha
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_USER=user
    #   - DB_PASSWORD=afZZs5DQzYegZFTeFLob
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./services/database/sql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    env_file:
      - ./.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: afZZs5DQzYegZFTeFLob
    #   MYSQL_DATABASE: reading-alpha
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: afZZs5DQzYegZFTeFLob
